name: AWS Amazon Linux 2 3.7.9
on: [push]
jobs:
  build:
    runs-on: amazonlinux
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.10
    - name: Install dependencies
      run: |
        make install
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make test
    - name: Format
      run: |
        make format
